server:
  port: 8088

spring:
  thymeleaf:
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/static/
#spring:
  application:
    name: microservice-consumer
  resources:
    static-locations: classpath:/static/,classpath:/templates/

eureka:
  client:
    register-with-eureka: true
    service-url: 
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
  instance:
    instance-id: microservice-consumer-8088
    prefer-ip-address: true     #访问路径可以显示IP地址

feign: 
  hystrix: 
    enabled: true